### ISSUE TITLE
Add Informations that which tables failed and its reason..

### ISSUE THREAD

**Issue by shivamsharma** [ShahSunny/SqlShift#17]

**Comment by ShahSunny** [comment]
Thanks for opening this issue, This is really required..

Let us build a module for monitoring and alerting in this project.

We can also add UI-server in the project, Which will manage the history of the runs, Including the details like this for each run,
- Time taken for data extraction from MySQL,
- Time taken by Spark for transformation
- Time taken for Redshift ingestion.
- The number of executor project received from YARN. 
- UI can also track the progress in realtime.

Once we have these data, we can even implement adaptive alerting where if table takes more time than it's last 10 runs then it can automatically send alert.

Design choice is, Shall we make UI-server module inside the project or create a separate project?
Making a UI-server outside has an advantage of using it for other Redshift ingests like Mongo-Redshift. Might be we can first build it for this project itself, once it gets matured we can take it out and make a new project out of it.
